version: '3.3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: pestova/profile_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
  nginx:
    image: pestova/profile_infra
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
  redis:
    image: redis:7.0.5-alpine
  celery:
    image: pestova/profile_backend
    command: celery -A profile_backend worker --loglevel=info
    volumes:
      - ./project:/usr/src/app
    env_file: .env
    depends_on:
      - backend
      - redis
