# Generated by Django 3.2.16 on 2024-05-22 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='ImageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_image', models.ImageField(upload_to='', verbose_name='Аватар пользователя s')),
                ('medium_image', models.ImageField(upload_to='', verbose_name='Аватар пользователя m')),
                ('pofile_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
