# Generated by Django 3.2.16 on 2024-05-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240522_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageuser',
            old_name='medium_image',
            new_name='image_medium',
        ),
        migrations.RenameField(
            model_name='imageuser',
            old_name='small_image',
            new_name='image_small',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='Аватар'),
        ),
    ]
