# Generated by Django 3.2.16 on 2024-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240523_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuser',
            name='image',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', upload_to='', verbose_name='Аватар пользователя'),
        ),
    ]
