# Generated by Django 3.2.16 on 2024-05-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240523_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='otp_code',
            field=models.IntegerField(default=111111),
        ),
        migrations.DeleteModel(
            name='ImageUser',
        ),
    ]
