# Generated by Django 3.2.16 on 2024-05-25 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240524_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='otp_code',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='username',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=0, max_length=6, verbose_name='Код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время выдачи кода')),
                ('used', models.BooleanField(default=True, verbose_name='Использован да/нет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код',
                'verbose_name_plural': 'Коды',
            },
        ),
    ]
