# Generated by Django 3.2.16 on 2024-05-26 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240525_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='used',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='block_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время окончания блокировки профиля'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='count_attempt',
            field=models.SmallIntegerField(blank=True, default=3, verbose_name='Количество попыток'),
        ),
    ]
